management:
  security:
    enabled: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug

spring:
  datasource:
    url: "jdbc:snowflake://nc94367.us-east-1.snowflakecomputing.com/?warehouse=NC_DW_HEALTH_API_EXPERIMENTS&db=NC_GC_STAGING&schema=GC"
#    url: "jdbc:snowflake://nc94367.us-east-1.snowflakecomputing.com/?warehouse=NC_DW_HEALTH_API_EXPERIMENTS&db=datalab_staging&schema=KRISH"
    username: ${SF_USER}
    password: ${SF_PASSWORD}
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
