hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-demo
      server-version: 1.0.0
      implementation-description: FHIR demo server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
management:
  security:
    enabled: false

