hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-demo
      server-version: 1.0.0
      implementation-description: FHIR demo server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
management:
  security:
    enabled: false

# HTTP server configuration
server:
  tomcat:
    threads:
      max: 200

# default DB connections pool settings
spring:
  datasource:
# hikari seems to be the default connection pool
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 1
      maximum-pool-size: 200
# tomcat used to be default, keep these setting for now
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 200
      max-idle: 15
      min-idle: 8
