hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: Spring Boot Jersey Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
management:
  security:
    enabled: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug


spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/navcan_development"
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
